### ISSUE TITLE
Web App Media Query

### ISSUE THREAD

**Issue by urgent** [thisbounty/WebRTC-Frontend#1]
On index.html, use CSS media queries to hide dashboard. Instead show web app. 

login.html is good, no changes needed.

Create a simple interface. Logo, and one button for "Call"

Possible button design, unless you have better:

http://codepen.io/urgent/pen/PbzMLo

**Comment by Sebastp** [comment]
I'm working on it

**Comment by thisbounty** [comment]
To clarify, I just need to simulate a smart phone app.

When a user is on their phone, and goes to the website, I want it to look like an app on droid or iOS.

All I need is the text "Call 2 Search" centered on the page, about 1/3 down, and underneath it, about 1/2 down, a "Call" button.

No need to design logo. No extra pages. You can use a media query to hide the dashboard, and add html to the index.html page for the web app, which is hidden on desktop.
