### ISSUE TITLE
Web App -- Create Call

### ISSUE THREAD

**Issue by urgent** [thisbounty/WebRTC-Frontend#2]
Need to use OpenTok API to create a voice call

https://tokbox.com/developer/sdks/js/

Use GET /calls/new api endpoint to get tokbox authentication token.

https://tokbox.com/developer/guides/connect-session/js/#connecting

Only need audio, no video:
https://tokbox.com/developer/guides/audio-video/js/#voice
https://tokbox.com/developer/tutorials/web/basic-video-chat/step-4/

Full stream instructions, and once again, friendly reminder, no video is required:
https://tokbox.com/developer/guides/publish-stream/js/index.html#create_publisher

**Comment by adammankowski1** [comment]
Going to do this one.
