### ISSUE TITLE
Desktop App -- Call Connect

### ISSUE THREAD

**Issue by urgent** [thisbounty/WebRTC-Frontend#3]
On Desktop App, incoming calls show a button in the "Status" column. Need to bind this button to two actions:

Call /calls/connect/:id to update call status across desktop app

Connect to tokbox session with voice only. See work on #2 for opentok connect implementation. Can possibly share javascript functions.

**Comment by MeQuake** [comment]
I take this one

**Comment by thisbounty** [comment]
Please see Tokbok Spike commits:

https://github.com/thisbounty/WebRTC-Frontend/commit/1140275a31f9490d6490e5fb282899003ff9aca0

Click event is captured for the button, and started work on opentok integration.

**Comment by thisbounty** [comment]
Taken by MeQuake
