### ISSUE TITLE
Desktop App -- Server Side events

### ISSUE THREAD

**Issue by urgent** [thisbounty/WebRTC-Frontend#4]
Need to handle Server Side Events.

When a desktop user clicks the "Incoming" button, the /calls/connect/:id endpoint is requested. This endpoint will send a server side event out to all desktop users. See:

https://github.com/thisbounty/WebRTC-Frontend/blob/master/assets/pages/scripts/table-datatables-responsive.js#L146-L151

This server side event needs to be handled, so that "Status" column in the "Calls" table is updated. 

Datatables.js provides an api for updating rows. You may need that. If not, drop down to jquery.

**Comment by adammankowski1** [comment]
Taking this one
