### ISSUE TITLE
Desktop App -- Authentication

### ISSUE THREAD

**Issue by thisbounty** [thisbounty/WebRTC-Frontend#5]
On index.html, redirect to login.html if no local storage exists for loopback auth token

https://html.spec.whatwg.org/multipage/webstorage.html#dom-localstorage

Local storage set here. I believe method is localStorage.getItem() to read token:

https://github.com/thisbounty/WebRTC-Frontend/blob/master/assets/pages/scripts/login.js#L51

**Comment by thisbounty** [comment]
See how token is accessed from local storage here:

https://github.com/thisbounty/WebRTC-Frontend/commit/902007312d5911596db7b813822a1a6915548ae5

To complete, work with App.init()

Try getting token, and if it is empty, redirect to login

**Comment by Emkacf** [comment]
I will take it
