### ISSUE TITLE
Desktop App -- Redirect

### ISSUE THREAD

**Issue by thisbounty** [thisbounty/WebRTC-Frontend#6]
Improve redirect when user is not logged in.

Right now popup shows from datatables.js. User needs to clear.

Perhaps it could be fixed by changing:

https://github.com/thisbounty/WebRTC-Frontend/blob/master/assets/pages/scripts/table-datatables-responsive.js#L142

to $(window).load() {
}

**Comment by Emkacf** [comment]
taking it

**Comment by Emkacf** [comment]
done

**Comment by thisbounty** [comment]
ty!
