### ISSUE TITLE
Desktop App -- Signup

### ISSUE THREAD

**Issue by thisbounty** [thisbounty/WebRTC-Frontend#7]
Need signup form on frontend, for signing up new users.

Loopback api can create new users with a POST to /users . Try with below fields, if there is an error, we'll look into api.

 {
    "username": "admin@admin.com",
    "email": "admin@admin.com",
    "firstName": "Admin",
    "lastName": "User"
  }

Also need to send email. 

http://stackoverflow.com/questions/24553164/strongloop-loopback-send-email#35353152

Need a mail server. AWS SES is clunky and cumbersome. Let's look at mailgun:
http://www.mailgun.com/

**Comment by Emkacf** [comment]
I can take it

**Comment by Emkacf** [comment]
done

**Comment by thisbounty** [comment]
ty!
